name: plantdoc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.1  
  http: ^1.2.0

  google_maps_flutter: ^2.14.2
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.12.1
  image_picker: ^1.0.4
  image: ^4.1.3
  camera: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/models/diseaseDetection.tflite
    - assets/models/labels.txt
    - assets/images/plantdoc_logo.png
    - assets/images/plant_bg.jpg
    - assets/images/healthy.jpg
    - assets/images/bacterial.JPG
    - assets/images/cercospora.JPG
    - assets/images/anthracnose.jpg
    - assets/images/curl_virus.JPG
    - assets/images/nutrition.JPG
    - assets/images/white_spot.JPG

flutter_native_splash:
  color: "#00a651"
  image: assets/logo.png
  android: true
  ios: true