// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6anPpTLlq9PJ9pwDoslQhul0PnnStZVo',
    appId: '1:63674742640:web:e66fdff622677fab2f01b5',
    messagingSenderId: '63674742640',
    projectId: 'plantdoc-4d7f0',
    authDomain: 'plantdoc-4d7f0.firebaseapp.com',
    storageBucket: 'plantdoc-4d7f0.firebasestorage.app',
    measurementId: 'G-MPHMYYJFWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC71TyfDvUzdZ_HMSjl240F-N1I78Pv_nw',
    appId: '1:63674742640:android:56e4bc4c8963b5aa2f01b5',
    messagingSenderId: '63674742640',
    projectId: 'plantdoc-4d7f0',
    storageBucket: 'plantdoc-4d7f0.firebasestorage.app',
  );
}
